return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "black",
      "clangd",
      "codespell",
      "css-lsp",
      "stylua",
      "json-lsp",
      "shellcheck",
      "shfmt",
      "gopls",
      "gofumpt",
      "flake8",
      "pyright",
      "rust-analyzer",
      "rustfmt",
      "prettierd",
      "html-lsp",
      "vim-language-server",
      "yaml-language-server",
      "dockerfile-language-server",
      "tailwindcss-language-server",
      "lua-language-server",
      "typescript-language-server",
    },
  },
}
